# Generated by Django 4.2.1 on 2023-11-07 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="bookInstantly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=100)),
                ("number", models.CharField(max_length=10)),
                ("pickAddress", models.CharField(max_length=255)),
                ("pickDate", models.DateField()),
                ("pickTime", models.TimeField()),
                ("dropAddress", models.CharField(max_length=255)),
                ("dropDate", models.DateField()),
                ("dropTime", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Processing", "Processing"),
                            ("Accepted", "Accepted"),
                            ("Cancelled", "Cancelled"),
                            ("Decline", "Decline"),
                            ("Done", "Done"),
                        ],
                        default="Processing",
                        max_length=150,
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.vehicleregistration",
                    ),
                ),
            ],
        ),
    ]
