# Generated by Django 4.2.1 on 2023-11-08 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookinstantly", old_name="dropDate", new_name="FromDate",
        ),
        migrations.RenameField(
            model_name="bookinstantly", old_name="dropTime", new_name="FromTime",
        ),
        migrations.RenameField(
            model_name="bookinstantly", old_name="pickDate", new_name="UntilDate",
        ),
        migrations.RenameField(
            model_name="bookinstantly", old_name="pickTime", new_name="UntilTime",
        ),
        migrations.RemoveField(model_name="bookinstantly", name="dropAddress",),
        migrations.RemoveField(model_name="bookinstantly", name="pickAddress",),
    ]
