# Generated by Django 4.2.1 on 2023-11-08 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_rename_dropdate_bookinstantly_fromdate_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookinstantly", old_name="FromDate", new_name="dropDate",
        ),
        migrations.RenameField(
            model_name="bookinstantly", old_name="FromTime", new_name="dropTime",
        ),
        migrations.RenameField(
            model_name="bookinstantly", old_name="UntilDate", new_name="pickDate",
        ),
        migrations.RenameField(
            model_name="bookinstantly", old_name="UntilTime", new_name="pickTime",
        ),
    ]
