# Generated by Django 4.2.1 on 2024-01-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_customerpayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinstantly",
            name="status",
            field=models.CharField(
                choices=[
                    ("Processing", "Processing"),
                    ("Accepted", "Accepted"),
                    ("Cancelled", "Cancelled"),
                    ("Decline", "Decline"),
                    ("Paid", "Paid"),
                    ("Done", "Done"),
                ],
                default="Processing",
                max_length=150,
            ),
        ),
    ]
