# Generated by Django 4.2.1 on 2024-01-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_alter_bookinstantly_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinstantly",
            name="booking_duration",
            field=models.IntegerField(default=0),
        ),
    ]
