# Generated by Django 4.2.1 on 2024-01-05 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_bookinstantly_total_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customerpayment",
            old_name="payment_amount",
            new_name="total_paid_amount",
        ),
        migrations.AddField(
            model_name="customerpayment",
            name="commission_per",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customerpayment",
            name="vendor_payment",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customerpayment",
            name="vendor_payment_ts",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
