# Generated by Django 4.2.1 on 2024-02-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0009_alter_customerpayment_vendor_payment_ts"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                ("requested_amount", models.IntegerField()),
                ("paid_date", models.DateTimeField(blank=True, null=True)),
                ("request_status", models.CharField(default="Pending", max_length=50)),
                (
                    "customer_payments",
                    models.ManyToManyField(
                        related_name="payment_requests", to="services.customerpayment"
                    ),
                ),
            ],
        ),
    ]
