# Generated by Django 4.2.1 on 2024-02-07 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_userverificationstatus_reverify"),
        ("services", "0011_alter_paymentrequest_request_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="vehicleReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("rating", models.IntegerField(default=0)),
                ("timeStamp", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.vehicleregistration",
                    ),
                ),
            ],
        ),
    ]
