# Generated by Django 4.2.1 on 2023-11-07 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("cc", models.CharField(max_length=150)),
                ("year", models.CharField(max_length=150)),
                ("color", models.CharField(default="Black", max_length=150)),
                (
                    "transmission",
                    models.CharField(
                        choices=[
                            ("Manual", "Manual"),
                            ("Automatic", "Automatic"),
                            ("CVT", "CVT"),
                        ],
                        default="Manual",
                        max_length=150,
                    ),
                ),
                ("bootCapacity", models.CharField(max_length=150)),
                (
                    "carFuel",
                    models.CharField(
                        choices=[
                            ("Petrol", "Petrol"),
                            ("Diesel", "Diesel"),
                            ("Electric", "Electric"),
                        ],
                        default="Petrol",
                        max_length=150,
                    ),
                ),
                (
                    "features",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("Sunroof", "Sunroof"),
                            ("GPS", "GPS"),
                            ("All Wheel drive", "All Wheel drive"),
                            ("Heated seats", "Heated seats"),
                            ("Bluetooth", "Bluetooth"),
                            ("Apple CarPlay", "Apple CarPlay"),
                            ("Android Auto", "Android Auto"),
                            ("Backup camera", "Backup camera"),
                            ("Cruise Control", "Cruise Control"),
                            ("Push-Button Start", "Push-Button Start"),
                        ],
                        default=["Sunroof", "GPS", "Bluetooth"],
                        max_length=150,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("capacity", models.IntegerField()),
                (
                    "category",
                    models.CharField(
                        choices=[("car", "Car"), ("bike", "Bike"), ("cycle", "Cycle")],
                        max_length=5,
                    ),
                ),
                ("subcategory", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "image1",
                    models.ImageField(default="1", upload_to="accounts/vehicle_images"),
                ),
                (
                    "image2",
                    models.ImageField(default="1", upload_to="accounts/vehicle_images"),
                ),
                (
                    "image3",
                    models.ImageField(default="1", upload_to="accounts/vehicle_images"),
                ),
                (
                    "image4",
                    models.ImageField(default="1", upload_to="accounts/vehicle_images"),
                ),
                (
                    "image5",
                    models.ImageField(default="1", upload_to="accounts/vehicle_images"),
                ),
                (
                    "bluebookimg",
                    models.ImageField(default="1", upload_to="accounts/bluebookimg"),
                ),
                (
                    "citizenimg",
                    models.ImageField(default="1", upload_to="accounts/citizenimg"),
                ),
                ("isVerified", models.BooleanField(default=False)),
                ("available", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=150)),
                ("street", models.CharField(max_length=150)),
                ("postalcode", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=150)),
                (
                    "country",
                    models.CharField(
                        choices=[("Nepal", "Nepal")], default="Nepal", max_length=150
                    ),
                ),
                (
                    "user_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
