# Generated by Django 4.2.1 on 2024-01-21 05:13

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicleregistration",
            name="bootCapacity",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="vehicleregistration",
            name="carFuel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Petrol", "Petrol"),
                    ("Diesel", "Diesel"),
                    ("Electric", "Electric"),
                ],
                default="Petrol",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vehicleregistration",
            name="cc",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="vehicleregistration",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vehicleregistration",
            name="features",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("Sunroof", "Sunroof"),
                    ("GPS", "GPS"),
                    ("All Wheel drive", "All Wheel drive"),
                    ("Heated seats", "Heated seats"),
                    ("Bluetooth", "Bluetooth"),
                    ("Apple CarPlay", "Apple CarPlay"),
                    ("Android Auto", "Android Auto"),
                    ("Backup camera", "Backup camera"),
                    ("Cruise Control", "Cruise Control"),
                    ("Push-Button Start", "Push-Button Start"),
                ],
                default=["Sunroof", "GPS", "Bluetooth"],
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vehicleregistration",
            name="subcategory",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vehicleregistration",
            name="transmission",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Manual", "Manual"),
                    ("Automatic", "Automatic"),
                    ("CVT", "CVT"),
                ],
                default="Manual",
                max_length=150,
                null=True,
            ),
        ),
    ]
