# Generated by Django 4.2.3 on 2023-11-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleregistration',
            name='price',
            field=models.IntegerField(),
        ),
    ]
