# Generated by Django 4.2.3 on 2023-11-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_vehicleregistration_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleregistration',
            name='category',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('cycle', 'Cycle')], max_length=5),
        ),
    ]
