# Generated by Django 4.2.1 on 2024-01-31 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0002_alter_vehicleregistration_bootcapacity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserVerificationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="accounts/user_photos"
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "citizen_ship_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="accounts/citizenship_images"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
