# Generated by Django 4.2.1 on 2024-01-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userverificationstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="userverificationstatus",
            name="reverify",
            field=models.BooleanField(default=False),
        ),
    ]
