# Generated by Django 4.2.3 on 2023-11-05 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_vehicleregistration_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleregistration',
            name='subcategory',
            field=models.CharField(choices=[], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
