# Generated by Django 4.2.3 on 2023-11-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_vehicleregistration_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleregistration',
            name='bluebookimg',
            field=models.ImageField(default='1', upload_to='bluebookimg/'),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='citizenimg',
            field=models.ImageField(default='1', upload_to='citizenimg/'),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='image1',
            field=models.ImageField(default='1', upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='image2',
            field=models.ImageField(default='1', upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='image3',
            field=models.ImageField(default='1', upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='image4',
            field=models.ImageField(default='1', upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='image5',
            field=models.ImageField(default='1', upload_to='vehicle_images/'),
        ),
        migrations.AlterField(
            model_name='vehicleregistration',
            name='subcategory',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='VehicleImage',
        ),
    ]
