# Generated by Django 4.2.1 on 2024-01-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userverificationstatus_reverify"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userverificationstatus",
            name="reverify",
            field=models.BooleanField(default=True),
        ),
    ]
