# Generated by Django 4.2.3 on 2023-11-05 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_vehicleregistration_bluebookimg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=150)),
                ('postalcode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=150)),
                ('country', models.CharField(choices=[('Nepal', 'Nepal')], default='Nepal', max_length=150)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
