# Generated by Django 4.2.1 on 2023-11-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_vehicleregistration_bluebookimg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleregistration",
            name="isVerified",
            field=models.BooleanField(default=False),
        ),
    ]
